<?php

/**
 * @file
 * Contains barcode_reader.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function barcode_reader_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the barcode_reader module.
    case 'help.page.barcode_reader':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Scan barcode to buy the product.') . '</p>';
      return $output;

    default:
  }
}

function barcode_reader_preprocess_page(&$variables) {
	
  if ($variables['is_front']) {
    unset($variables['page']['sidebar_first']['barcodereaderblock']);
  }
}
